services:
  stirling-pdf:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./configs:/configs
      - ./trainingData:/usr/share/tessdata
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=admin
      - SECURITY_INITIALLOGIN_PASSWORD=stirling
      - HOST='::'
      - PORT=8080
    networks:
      default:
        aliases:
          - stirling-pdf

networks:
  default:
    enable_ipv6: true
    driver: bridge
